language: node_js
node_js:
- v6.9.1
- v5
deploy:
  api_key:
    secure: X0Rd8epWXkc2DunIKufktFF+dCcyfnIB1p5Gw+Uja7LGmuOeWcSr5NJVQlmf7Be4rxGRPGOOV0b5Zd9FifJ5+veYVMS9DTPaLSpTxPVLHYFSXRtTl1HrTFAVdHEHhWV245Ec9DUs4nSeu6g4IWUu9spiG3moThucPjv9Krv2Xm0IbMK5DiYzwvGpJnU+HbcREP4L+ptcU3dVliDZzSxfu5Q/Dy8y8zq3DBIKHsfptmhhG2PXk128EZ5WYsx5StcgG5D19Y/Gq/DIm+9RAjiVLN0JPPa9evKRwKC7V+e10WibGPsFGqu8nBsNY6GNqHd4AG9MMK9LaTja2kFm3TTSaLpjrIYSWDlAMdz9a8uigmVJkRIfoDfX6fSw6Qq68guYB2a+vgfqGPbeoCPwwldtzVzC+bFGtbmkEsk+DwXkXroodvOzUnjVINpIDkCDRvLQQq7fl5Hq6N5I2U8wtTozoaf3K3h2mm2VHL2gyF3w/IPvNPjxxg/PyP686xkM/i/fmhkuZVWt0ZuVPBaJZH5K0rrU3LTrQgOuvvUTsNC7dUpYr27ggTxccTdPvbjtVpAe/OFuRGqs8j14U5DlnJwmBmcrec94oDFxe5WAi45FcZW7wPbI8Zc17Xdw2eNKKw4XZFBzBbNg4sMCk0ppwHnlMBwpqXqBuuOd0boUSTlTSI0=
  on:
    tags: true
    branch: master
